version: "3.8"

services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - my_network
  info:
    build: ./auth
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - broker
    environment:
      RABBITMQ_HOST: broker
      RABBITMQ_PORT: 5672
    networks:
      - my_network

  provider-1:
    build: ./provider
    restart: on-failure
    ports:
      - "9000:9000"
    depends_on:
      - broker
    environment:
      RABBITMQ_HOST: broker
      RABBITMQ_PORT: 5672
    networks:
      - my_network

  provider-2:
    build: ./provider
    restart: on-failure
    ports:
      - "9001:9000"
    depends_on:
      - broker
    environment:
      RABBITMQ_HOST: broker
      RABBITMQ_PORT: 5672
    networks:
      - my_network

  provider-3:
    build: ./provider
    restart: on-failure
    ports:
      - "9002:9000"
    depends_on:
      - broker
    environment:
      RABBITMQ_HOST: broker
      RABBITMQ_PORT: 5672
    networks:
      - my_network

volumes:
  broker-data:

networks:
  my_network:
    driver: bridge
